### ISSUE TITLE
克隆下来后跑不起来service

### ISSUE THREAD

**Issue by weicheng59** [NCZkevin/chatglm-web#3]
python main.py --device='cpu' --host='127.0.0.1' --port='7680'
Traceback (most recent call last):
  File "/Users/weicheng/Documents/Dev/llm/chatglm-web/service/main.py", line 16, in <module>
    import knowledge
  File "/Users/weicheng/Documents/Dev/llm/chatglm-web/service/knowledge.py", line 4, in <module>
    ix = storage.open_index()
  File "/opt/homebrew/lib/python3.10/site-packages/whoosh/filedb/filestore.py", line 176, in open_index
    return indexclass(self, schema=schema, indexname=indexname)
  File "/opt/homebrew/lib/python3.10/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/opt/homebrew/lib/python3.10/site-packages/whoosh/index.py", line 618, in read
    raise EmptyIndexError("Index %r does not exist in %r"
whoosh.index.EmptyIndexError: Index 'MAIN' does not exist in FileStorage('knowdata')

**Comment by NCZkevin** [comment]
建议先把main.py里的最后这行`gen_data.gen_whoosh_data()`注释掉，回去我再复现看看是哪里有问题

**Comment by NCZkevin** [comment]
找到问题了，先运行一下`python gen_data.py`就可以了，我先删掉启动的时候生成索引
